# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170713_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedata',
            name='data',
            field=models.CharField(max_length=120),
        ),
    ]
